name: Auto Run Node.js

on:
  push:
    branches:
      - main
  workflow_dispatch:  # Agar bisa dijalankan manual juga dari GitHub UI

jobs:
  run-node:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Run script
        run: node server.js  # Ganti dengan file utama Anda
